version: "3"
services: 
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"
    kafka:
        build: .
        ports: 
            - "9092"
    environment: 
        KAFKA_ADVERTISED_HOST_NAME: Kafka
        KAFKA_ZOOKEEPER_CONNECT: zookepper:2181
        volumes:
            - /var/run/docker.sock:var/run/docker.sock